#include "main.c"
#include "treecc/tokenizer.c"
#include "treecc/parser.c"
#include "treecc/c_types.c"
#include "treecc/node.c"
#include "treecc/scope_symbol_table.c"
#include "core/build_core.c"
// #include "treecc/x64.c"
